name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "This is a read-only repository. Please submit your PR on the https://github.com/stellarwp/licensing-api-client-monorepo repository.<br><br>Thanks!"
